### PR TITLE
Add `TokenKind::ProofLine`

### PR DESCRIPTION
**Pull request by JOT85**

### CODE REVIEW

**Comment by sharnoff** [comment]
The comments added to 'verify/mod.rs' aren't related to the subject of the PR... could those be a separate commit to master?

**Comment by JOT85** [comment]
> The comments added to 'verify/mod.rs' aren't related to the subject of the PR... could those be a separate commit to master?

They were from the rebase.

**Comment by JOT85** [comment]
The last commit was to remove a duplicate definition of proof, the auto-merge duplicated it.

**Comment by sharnoff** [comment]
> > The comments added to 'verify/mod.rs' aren't related to the subject of the PR... could those be a separate commit to master?

> They were from the rebase.

I'm not sure I follow - I'm struggling to find those changes elsewhere.

**Comment by JOT85** [comment]
> > > The comments added to 'verify/mod.rs' aren't related to the subject of the PR... could those be a separate commit to master?
> 
> > They were from the rebase.
> 
> I'm not sure I follow - I'm struggling to find those changes elsewhere.

Some of the comments were removed in https://github.com/tc-lang/trenchcoat/commit/71b569860e81204821370d57c196a7610e731f5d#diff-9a66253157a0bd30d29a4741968efdad however I made a mistake whilst merging and left them in.

**Pull request merged**
